version: '3'
services:
  notebook:
    build:
      context: images/zeppelin
    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
    - /opt/zeppelin/notebook
    - /opt/zeppelin/logs

  webconsole:
    build:
      context: images/webconsole
    ports:
      - "7681:7681"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
