---
- name: ensure datasets exists
  file:
    path: /datasets/dataset=donation/blocks/
    state: directory

- name: download datasets
  get_url:
    url: https://s3-eu-west-1.amazonaws.com/{{ bucket }}/datasets/dataset%3Ddonation/blocks/{{ item }}
    dest: /datasets/dataset=donation/blocks/{{ item }}
    mode: 0666
  with_items:
    - block_1.csv
    - block_2.csv
    - block_3.csv
    - block_4.csv

- name: download datasets readme
  get_url:
    url: https://s3-eu-west-1.amazonaws.com/{{ bucket }}/datasets/dataset%3Ddonation/documentation
    dest: /datasets/dataset=donation/documentation
    mode: 0666

- name: download datasets yellow_tripdata on year 2013
  get_url:
    url: https://s3-eu-west-1.amazonaws.com/{{ bucket }}/datasets/dataset%3Ddataset=yellow_tripdata/year=2013/{{ item }}
    dest: /datasets/dataset=yellow_tripdata/{{ item }}
    mode: 0666
  with_items:
    - yellow_tripdata_2013-01.csv

- name: download dataset nyc-borough-boundaries-polygon.geojson
  get_url:
    url: https://s3-eu-west-1.amazonaws.com/{{ bucket }}/datasets/dataset%3Dnyc-borough-boundaries/nyc-borough-boundaries-polygon.geojson
    dest: /datasets/dataset=nyc-borough-boundaries/nyc-borough-boundaries-polygon.geojson
    mode: 0666
